//This essentially helps test the api if it's working by making crud requests 
// add a newline and ### to separate two requests
GET http://localhost:5000/users

###

POST http://localhost:5000/users

Content-Type: application/json
{
    "firstName" : "Mihir",
    "lastName" : "Deshpande",
    "age" : 22,
    "promember" : true
}

